services:

    kokoro:
        image: ghcr.io/remsky/kokoro-fastapi-cpu:latest   
        container_name: kokoro
        restart: unless-stopped
        ports:
            - "8880:8880"

            
#    kokoro:
#        image: ghcr.io/remsky/kokoro-fastapi-gpu:latest   # GPU Nvidia
#        container_name: kokoro
#        restart: unless-stopped
#        ports:
#            - "8880:8880"
#        deploy:
#            resources:
#                reservations:
#                    devices:
#                        - driver: nvidia
#                          count: all
#                          capabilities:
#                              - gpu
